# Generated by Django 4.2.15 on 2024-08-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Role',
            field=models.CharField(choices=[('PT', 'Portiere'), ('DF', 'Difensore'), ('CC', 'Centrocampista'), ('AT', 'Attaccante')], default='PT', max_length=2),
            preserve_default=False,
        ),
    ]
