# Generated by Django 4.2.15 on 2024-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0002_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Estero')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
