# Generated by Django 4.2.15 on 2024-08-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0003_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RealTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('A', 'Serie A'), ('B', 'Altra serie')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Nsvincoli', models.IntegerField()),
                ('Ncarognate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series')),
                ('Session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.session')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_date', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('O', 'Aperto'), ('C', 'Chiuso')], max_length=1)),
                ('Competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Amount', models.IntegerField()),
                ('Best', models.BooleanField(default=False)),
                ('Ghost', models.BooleanField(default=False)),
                ('Carognata', models.BooleanField(default=False)),
                ('Market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.market')),
                ('Player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.player')),
                ('Session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.session')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='RealTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.realteam'),
        ),
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team'),
        ),
    ]
