# Generated by Django 4.2.15 on 2024-08-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0004_competition_realteam_series_session_team_market_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
