# Generated by Django 4.2.15 on 2024-09-03 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0005_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='Expiration_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
