# Generated by Django 4.2.15 on 2024-09-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0007_remove_bet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='Slot',
            field=models.TextField(default='p1', max_length=2),
            preserve_default=False,
        ),
    ]
