# Generated by Django 4.2.15 on 2024-09-04 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l4m_app', '0008_bet_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Users',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
