# Generated by Django 4.2.15 on 2024-09-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0009_team_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='Session_date',
            new_name='Name',
        ),
    ]
