# Generated by Django 4.2.15 on 2024-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0010_rename_session_date_market_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='Expiration_Date',
            field=models.TextField(max_length=100),
        ),
    ]
