# Generated by Django 4.2.15 on 2024-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0011_alter_bet_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Wages_amount', models.IntegerField()),
                ('Purchases_amount', models.IntegerField()),
            ],
        ),
    ]
