# Generated by Django 4.2.15 on 2024-11-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0012_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.balance'),
        ),
    ]
