# Generated by Django 4.2.15 on 2024-11-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0013_team_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.balance'),
        ),
    ]
