# Generated by Django 4.2.15 on 2024-12-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0014_remove_team_balance_balance_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='IsExpired',
            field=models.BooleanField(default=False),
        ),
    ]
