# Generated by Django 4.2.15 on 2025-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0015_bet_isexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='IsRaised',
            field=models.BooleanField(default=False),
        ),
    ]
