# Generated by Django 4.2.15 on 2025-01-08 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0016_bet_israised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team'),
        ),
    ]
