# Generated by Django 4.2.15 on 2025-02-15 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0017_alter_balance_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Years', models.IntegerField()),
                ('Jersey_num', models.IntegerField()),
                ('Quot', models.IntegerField()),
                ('Suspended', models.BooleanField(default=False)),
                ('Last_bet_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.bet')),
                ('Player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.player')),
                ('Team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.team')),
            ],
        ),
    ]
