# Generated by Django 4.2.15 on 2025-02-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0018_squads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squads',
            old_name='Last_bet_id',
            new_name='Last_bet',
        ),
        migrations.RenameField(
            model_name='squads',
            old_name='Player_id',
            new_name='Player',
        ),
    ]
