# Generated by Django 4.2.15 on 2025-01-23 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Team',
        ),
    ]
