# Generated by Django 4.2.15 on 2025-02-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0019_remove_notification_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='Best',
        ),
    ]
