# Generated by Django 4.2.15 on 2025-02-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0019_rename_last_bet_id_squads_last_bet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squads',
            old_name='Team_id',
            new_name='Team',
        ),
    ]
