# Generated by Django 4.2.15 on 2025-02-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0020_remove_bet_best'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now=True)),
                ('Amount', models.IntegerField()),
                ('Ghost', models.BooleanField(default=False)),
                ('Carognata', models.BooleanField(default=False)),
                ('Expiration_Date', models.TextField(max_length=100)),
                ('Slot', models.TextField(max_length=2)),
                ('IsExpired', models.BooleanField(default=False)),
                ('IsRaised', models.BooleanField(default=False)),
                ('Market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.market')),
                ('Player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.player')),
                ('Session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.session')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
    ]
