# Generated by Django 4.2.15 on 2025-02-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0020_rename_team_id_squads_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squads',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Jersey_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.player'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Quot',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.team'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='Years',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='Purchases_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='Wages_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='Players',
            field=models.ManyToManyField(to='l4m_app.player'),
        ),
    ]
