# Generated by Django 4.2.15 on 2025-03-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0021_alter_squads_amount_alter_squads_jersey_num_and_more'),
        ('l4m_app', '0021_bet_history'),
    ]

    operations = [
    ]
