# Generated by Django 4.2.15 on 2025-03-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0022_merge_20250306_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet_history',
            name='IsExpired',
        ),
        migrations.RemoveField(
            model_name='bet_history',
            name='IsRaised',
        ),
        migrations.RemoveField(
            model_name='bet_history',
            name='Slot',
        ),
    ]
