# Generated by Django 4.2.15 on 2025-03-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0022_merge_20250306_2340'),
        ('l4m_app', '0023_remove_bet_history_isexpired_and_more'),
    ]

    operations = [
    ]
