# Generated by Django 4.2.15 on 2025-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0023_remove_bet_history_isexpired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='IsOfficial',
            field=models.BooleanField(default=False),
        ),
    ]
