# Generated by Django 4.2.15 on 2025-07-27 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
#        ('l4m_app', '0022_merge_20250306_2340'),
        ('l4m_app', '0024_bet_isofficial'),
    ]

    operations = [
    ]
