# Generated by Django 4.2.15 on 2025-05-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0024_bet_isofficial'),
        ('l4m_app', '0024_merge_20250309_0120'),
    ]

    operations = [
    ]
