# Generated by Django 4.2.15 on 2025-06-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0024_bet_isofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='Purchases_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='Wages_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='Players',
            field=models.ManyToManyField(to='l4m_app.player'),
        ),
    ]
