# Generated by Django 4.2.15 on 2025-06-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0025_market_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='Players',
            field=models.ManyToManyField(to='l4m_app.player'),
        ),
    ]
