# Generated by Django 4.2.15 on 2025-07-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
       ('l4m_app', '0025_balance_purchases_max_balance_wages_max_and_more'),
        # ('l4m_app', '0024_bet_isofficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Real_calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('Competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
                ('RealTeamAway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='l4m_app.realteam')),
                ('RealTeamHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='l4m_app.realteam')),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line', models.CharField()),
                ('Version', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
    ]
