# Generated by Django 4.2.15 on 2025-06-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0025_market_players'),
        ('l4m_app', '0025_merge_0024_bet_isofficial_0024_merge_20250309_0120'),
    ]

    operations = [
    ]
