# Generated by Django 4.2.15 on 2025-07-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0026_real_calendar_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='Day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
