# Generated by Django 4.2.15 on 2025-07-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0027_lineup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='Line',
            field=models.CharField(max_length=2000),
        ),
    ]
