# Generated by Django 4.2.15 on 2025-07-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0028_alter_lineup_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Team',
        ),
    ]
