# Generated by Django 4.2.15 on 2025-08-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0029_remove_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='Series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series'),
        ),
        migrations.AddField(
            model_name='series',
            name='Competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition'),
        ),
        migrations.AddField(
            model_name='session',
            name='Market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.market'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='Series',
        ),
        migrations.AddField(
            model_name='team',
            name='Series',
            field=models.ManyToManyField(to='l4m_app.series'),
        ),
    ]
