# Generated by Django 4.2.15 on 2025-08-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0030_market_series_series_competition_session_market_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Session',
        ),
    ]
