# Generated by Django 4.2.15 on 2025-08-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0031_remove_team_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='Competition',
        ),
#        migrations.RemoveField(
 #           model_name='market',
  #          name='Players',
   #     ),
    ]
