# Generated by Django 4.2.15 on 2025-08-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0032_remove_market_competition_remove_market_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='End',
            field=models.DateTimeField(null=True),
        ),
    ]
