# Generated by Django 4.2.15 on 2025-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0033_session_begin_session_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='Players',
            field=models.ManyToManyField(to='l4m_app.player'),
        ),
    ]
