# Generated by Django 4.2.15 on 2025-08-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0034_market_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='Players',
            field=models.ManyToManyField(related_name='bet_player', to='l4m_app.player'),
        ),
    ]
