# Generated by Django 4.2.15 on 2025-08-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0035_bet_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='Players',
        ),
    ]
