# Generated by Django 4.2.15 on 2025-08-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0036_remove_bet_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.market')),
                ('Player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.player')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='MarkPlayers',
            field=models.ManyToManyField(related_name='markplayers', through='l4m_app.Mark_Players', to='l4m_app.player'),
        ),
    ]
