# Generated by Django 4.2.15 on 2025-08-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0037_mark_players_market_markplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='Mark_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.mark_players'),
        ),
    ]
