# Generated by Django 4.2.15 on 2025-08-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0038_bet_mark_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='N_carognate',
            field=models.PositiveSmallIntegerField(default=3, null=True),
        ),
    ]
