# Generated by Django 4.2.15 on 2025-08-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0039_rename_players__market_players_balance_n_carognate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='N_carognate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
