# Generated by Django 4.2.15 on 2025-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0040_balance_purchases_max_balance_wages_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='HideLineup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineup',
            name='ModNoGk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='Role',
            field=models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], max_length=2),
        ),
    ]
