# Generated by Django 5.2.4 on 2025-08-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0041_lineup_hidelineup_lineup_modnogk_alter_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Vote', models.FloatField(default=0.0)),
                ('GoalSc', models.IntegerField(default=0)),
                ('GoalTa', models.IntegerField(default=0)),
                ('GoalDe', models.IntegerField(default=0)),
                ('PenSc', models.IntegerField(default=0)),
                ('PenMi', models.IntegerField(default=0)),
                ('PenSa', models.IntegerField(default=0)),
                ('Own', models.IntegerField(default=0)),
                ('Yel', models.IntegerField(default=0)),
                ('Red', models.IntegerField(default=0)),
                ('AssS', models.IntegerField(default=0)),
                ('AssH', models.IntegerField(default=0)),
                ('AssL', models.IntegerField(default=0)),
                ('AssP', models.IntegerField(default=0)),
                ('SubJ', models.IntegerField(default=0)),
                ('Sub', models.FloatField(default=0.0)),
                ('Competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
                ('Player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.player')),
            ],
        ),
    ]
