# Generated by Django 5.2.4 on 2025-08-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0042_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('Stage', models.CharField(max_length=50)),
                ('HomeAway', models.BooleanField(default=False)),
                ('Overtime', models.BooleanField(default=False)),
                ('Penalties', models.BooleanField(default=False)),
                ('Competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
            ],
            options={
                'db_table': 'l4m_app_competition_calendar',
            },
        ),
    ]
