# Generated by Django 5.2.4 on 2025-08-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0043_competitioncalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AwayTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='l4m_app.team')),
                ('CompetitionCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competitioncalendar')),
                ('HomeTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='l4m_app.team')),
            ],
            options={
                'db_table': 'l4m_app_matches_calendar',
            },
        ),
    ]
