# Generated by Django 5.2.4 on 2025-08-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0044_matchescalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchesResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fp', models.FloatField()),
                ('FpO', models.FloatField()),
                ('Pen', models.IntegerField()),
                ('MatchesCalendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.matchescalendar')),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
            options={
                'db_table': 'l4m_app_matches_results',
            },
        ),
    ]
