# Generated by Django 5.2.4 on 2025-08-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0045_matchesresults'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='balance',
#            name='Purchases_max',
#            field=models.IntegerField(null=True),
#        ),
#        migrations.AddField(
#            model_name='balance',
#            name='Wages_max',
#            field=models.IntegerField(null=True),
#        ),
#        migrations.AddField(
#            model_name='market',
#            name='Players',
#            field=models.ManyToManyField(to='l4m_app.player'),
#        ),
        migrations.AddField(
            model_name='squads',
            name='Quarantine',
            field=models.BooleanField(default=False),
        ),
    ]
