# Generated by Django 5.2.4 on 2025-08-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0045_matchesresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesresults',
            name='Series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series'),
        ),
        migrations.AddField(
            model_name='squads',
            name='Quarantine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='RealTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.realteam'),
        ),
    ]
