# Generated by Django 5.2.4 on 2025-08-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0046_matchesresults_series_squads_quarantine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchesresults',
            name='Series',
        ),
        migrations.AddField(
            model_name='matchescalendar',
            name='Series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series'),
        ),
    ]
