# Generated by Django 4.2.15 on 2025-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0047_remove_matchesresults_series_matchescalendar_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Value', models.CharField()),
            ],
        ),
    ]
