# Generated by Django 4.2.15 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0048_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Live',
            field=models.BooleanField(default=False),
        ),
    ]
