# Generated by Django 4.2.15 on 2025-09-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0049_votes_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesresults',
            name='FpO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='matchesresults',
            name='Pen',
            field=models.IntegerField(null=True),
        ),
    ]
