# Generated by Django 4.2.15 on 2025-09-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0050_matches_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RankingLine', models.CharField()),
                ('Season', models.CharField()),
                ('Day', models.IntegerField(null=True)),
                ('Competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
                ('Series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series')),
            ],
        ),
    ]
