# Generated by Django 4.2.15 on 2025-09-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0051_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='LogoPath',
            field=models.CharField(null=True),
        ),
    ]
