# Generated by Django 4.2.15 on 2025-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0052_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='AssP',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
