# Generated by Django 4.2.15 on 2025-09-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0053_votes_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='YelRed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='AssP',
            field=models.IntegerField(default=0),
        ),
    ]
