# Generated by Django 4.2.15 on 2025-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0054_yelred'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='N_svincoli',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
