# Generated by Django 4.2.15 on 2025-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0055_balance_n_svincoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_history',
            name='Svincolo',
            field=models.BooleanField(default=False),
        ),
    ]
