# Generated by Django 4.2.15 on 2025-10-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0056_bet_history_svincolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet_history',
            name='Session_svincolo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_svincolo', to='l4m_app.session'),
        ),
    ]
