# Generated by Django 4.2.15 on 2025-10-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0057_bet_history_session_svincolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Role',
            field=models.CharField(choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], max_length=10),
        ),
    ]
