# Generated by Django 4.2.15 on 2025-10-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0058_alter_player_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='N_formazioni_non_schierate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
