# Generated by Django 4.2.15 on 2025-10-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0059_balance_n_formazioni_non_schierate'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='Live',
            field=models.BooleanField(default=False),
        ),
    ]
