# Generated by Django 4.2.15 on 2025-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0060_competition_active_competition_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Lineup',
            field=models.BooleanField(default=False),
        ),
    ]
