# Generated by Django 4.2.15 on 2025-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0061_competition_lineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesresults',
            name='BonusCap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='BonusDisc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='BonusHome',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='BonusPrest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='GrandTotal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='MissingSlots',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='ModNoGk',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='ModifierScore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='ModifierVal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Module',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='NGoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='OrigModule',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='PartialScore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Votes_Ris',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Votes_Tit',
            field=models.CharField(null=True),
        ),
    ]
