# Generated by Django 4.2.15 on 2025-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0062_matchesresults_bonuscap_matchesresults_bonusdisc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesresults',
            name='Home',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
