# Generated by Django 4.2.15 on 2025-11-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0063_alter_matchesresults_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='B11Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('B11Fp', models.FloatField()),
                ('Team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
    ]
