# Generated by Django 4.2.15 on 2025-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0064_b11results'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='LogoPath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
