# Generated by Django 4.2.15 on 2025-11-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0065_competition_logopath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elimination_stage', models.CharField(default='', null=True)),
                ('Competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.competition')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='Competition',
            field=models.ManyToManyField(through='l4m_app.Team_Competition', to='l4m_app.competition'),
        ),
    ]
