# Generated by Django 4.2.15 on 2025-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0066_team_competition_team_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ShortName',
            field=models.CharField(null=True),
        ),
    ]
