# Generated by Django 4.2.15 on 2025-11-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0067_team_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='Mark_player',
        ),
        migrations.RemoveField(
            model_name='market',
            name='MarkPlayers',
        ),
        migrations.DeleteModel(
            name='Mark_Players',
        ),
    ]
