# Generated by Django 4.2.15 on 2025-11-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0068_remove_bet_mark_player_remove_market_markplayers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='Late',
            field=models.BooleanField(default=False),
        ),
    ]
