# Generated by Django 4.2.15 on 2025-11-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0069_lineup_late'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='Late',
            new_name='LateEdit',
        ),
    ]
