# Generated by Django 4.2.15 on 2025-12-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0070_rename_late_lineup_lateedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='TotVote',
            field=models.FloatField(default=0.0),
        ),
    ]
