# Generated by Django 4.2.15 on 2025-12-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0071_vote_totvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncalendar',
            name='Suspended',
            field=models.BooleanField(default=False),
        ),
    ]
