# Generated by Django 4.2.15 on 2026-01-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0072_competitioncalendar_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesresults',
            name='ExtraTimePlayers',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='PenaltyPlayers',
            field=models.CharField(null=True),
        ),
    ]
