# Generated by Django 4.2.15 on 2026-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0073_matchesresults_extratimeplayers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='ShortName',
        ),
        migrations.AlterField(
            model_name='bet',
            name='Slot',
            field=models.TextField(max_length=10),
        ),
    ]
