# Generated by Django 4.2.15 on 2026-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0074_remove_team_shortname_alter_bet_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
