# Generated by Django 4.2.15 on 2026-01-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0075_series_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesresults',
            name='AggregateScore',
            field=models.FloatField(null=True),
        ),
    ]
