# Generated by Django 4.2.15 on 2026-01-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0076_matchesresults_aggregatescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesresults',
            name='AggregateScore',
            field=models.IntegerField(null=True),
        ),
    ]
