# Generated by Django 4.2.15 on 2026-01-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0077_alter_matchesresults_aggregatescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='IsGirone',
            field=models.BooleanField(default=True),
        ),
    ]
