# Generated by Django 4.2.15 on 2026-02-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0078_series_isgirone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='real_calendar',
            name='Competition',
        ),
        migrations.AddField(
            model_name='real_calendar',
            name='FT',
            field=models.BooleanField(default=False),
        ),
    ]
