# Generated by Django 4.2.15 on 2026-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0079_remove_real_calendar_competition_real_calendar_ft'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesresults',
            name='ET_Winner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Pen_Winner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Penalizations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchesresults',
            name='Winner',
            field=models.IntegerField(null=True),
        ),
    ]
