# Generated by Django 4.2.15 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0080_matchesresults_et_winner_matchesresults_pen_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncalendar',
            name='Num_Matches',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
