# Generated by Django 4.2.15 on 2026-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0081_competitioncalendar_num_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitioncalendar',
            name='Num_Matches',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
