# Generated by Django 4.2.15 on 2026-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0082_alter_competitioncalendar_num_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('LogoPath', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
