# Generated by Django 4.2.15 on 2026-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0083_othercompetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
