# Generated by Django 4.2.15 on 2026-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0084_team_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Start', models.DateField(null=True)),
                ('End', models.DateField(null=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
    ]
