# Generated by Django 4.2.15 on 2026-07-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0085_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
