# Generated by Django 4.2.15 on 2026-07-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0086_alter_ranking_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='Season',
        ),
        migrations.AddField(
            model_name='series',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
