# Generated by Django 4.2.15 on 2026-07-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0087_remove_ranking_season_series_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='squads',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='l4m_app.season'),
        ),
    ]
