# Generated by Django 4.2.15 on 2026-07-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0088_squads_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
