# Generated by Django 4.2.15 on 2026-07-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0089_balance_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_competition',
            name='Elimination_stage',
        ),
        migrations.AddField(
            model_name='team_competition',
            name='IsWinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team_competition',
            name='Notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team_competition',
            name='Points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_competition',
            name='Position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team_competition',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
