# Generated by Django 4.2.15 on 2026-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0090_remove_team_competition_elimination_stage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team_competition',
            unique_together={('Team', 'Competition', 'Season')},
        ),
        migrations.AddConstraint(
            model_name='team_competition',
            constraint=models.UniqueConstraint(fields=('Team', 'Competition', 'Season'), name='unique_team_competition'),
        ),
    ]
