# Generated by Django 4.2.15 on 2026-07-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0091_alter_team_competition_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team_competition',
            unique_together=set(),
        ),
    ]
