# Generated by Django 4.2.15 on 2026-07-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0092_alter_team_competition_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_competition',
            name='Series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series'),
        ),
    ]
