# Generated by Django 4.2.15 on 2026-07-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0093_team_competition_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_competition',
            name='Elimination_Stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team_competition',
            name='Series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.series'),
        ),
    ]
