# Generated by Django 4.2.15 on 2026-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0094_team_competition_elimination_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Expiration',
            field=models.IntegerField(default=48, null=True),
        ),
    ]
