# Generated by Django 4.2.15 on 2026-08-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0095_session_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Quotation',
            field=models.IntegerField(null=True),
        ),
    ]
