# Generated by Django 4.2.15 on 2026-08-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0096_player_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Surname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
