# Generated by Django 4.2.15 on 2026-08-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0097_alter_player_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ModifiedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
