# Generated by Django 4.2.15 on 2026-08-08 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('l4m_app', '0098_player_modifiedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
