# Generated by Django 4.2.15 on 2026-08-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0099_onlinepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_calendar',
            name='Season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
