# Generated by Django 4.2.15 on 2026-08-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0101_competitioncalendar_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='JustModified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
