# Generated by Django 4.2.15 on 2026-08-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0102_player_justmodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season'),
        ),
    ]
