# Generated by Django 4.2.15 on 2026-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0104_b11results_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_calendar',
            name='ExternalId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
