# Generated by Django 4.2.15 on 2026-08-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0105_real_calendar_externalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField()),
                ('C1', models.FloatField()),
                ('C2', models.FloatField()),
                ('C3', models.FloatField()),
                ('Pts', models.FloatField()),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.season')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.team')),
            ],
        ),
    ]
