# Generated by Django 4.2.15 on 2026-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0106_pdoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdoro',
            name='v22',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdoro',
            name='w11',
            field=models.FloatField(default=0.0),
        ),
    ]
