# Generated by Django 4.2.15 on 2026-09-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0107_pdoro_v22_pdoro_w11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('QuarantinableUntil', models.DateField()),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l4m_app.player')),
            ],
        ),
    ]
