# Generated by Django 4.2.15 on 2026-09-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0107_pdoro_v22_pdoro_w11'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdoro',
            name='Fp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pdoro',
            name='b11',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pdoro',
            name='b11_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pdoro',
            name='b11_low',
            field=models.FloatField(default=0.0),
        ),
    ]
