# Generated by Django 4.2.15 on 2026-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0108_quarantine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='IsQuarantine',
            field=models.BooleanField(default=False),
        ),
    ]
