# Generated by Django 4.2.15 on 2026-09-03 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0108_pdoro_fp_pdoro_b11_pdoro_b11_high_pdoro_b11_low'),
        ('l4m_app', '0109_bet_isquarantine'),
    ]

    operations = [
    ]
