# Generated by Django 4.2.15 on 2026-09-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0110_merge_20260903_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='InitialQuotation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Status',
            field=models.CharField(choices=[('A', 'Active'), ('E', 'Estero'), ('Q', 'Quarantena')], max_length=1),
        ),
    ]
