# Generated by Django 4.2.15 on 2026-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l4m_app', '0111_player_initialquotation_alter_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='b11results',
            name='AllSixBonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='CaptainBonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='Lineup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='ModifierFromNoGk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='b11results',
            name='ModifierScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='ModifierTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='Module',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='NoYellowBonus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='b11results',
            name='PartialScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
